version: '3.4'

services:
  tml-nft-bot:
    build: ./
    image: tml-nft-bot:${GITHUB_SHA}
    container_name: tml-nft-bot
    restart: always
    ports:
      - 127.0.0.1:8457:8000
    command:
      - bash
      - -c
      - |
        flask db init || true
        flask db migrate
        flask db upgrade
        gunicorn -b 0.0.0.0:8000 --statsd-host=statsd-exporter:9125 --statsd-prefix=tml-nft-bot -w 2 --timeout 10 --reload --preload nft:app
    environment:
      PYTHONUNBUFFERED: 1
    secrets:
      - source: env-file
        target: /app/.env

  statsd-exporter:
    image: prom/statsd-exporter:v0.22.4
    container_name: statsd-exporter
    ports:
      - "127.0.0.1:9102:9102"
    volumes:
      - ./conf/statsd.conf:/statsd/statsd.conf
    command:
      - --statsd.mapping-config=/statsd/statsd.conf
    networks:
      - prometheus_back-tier

secrets:
  env-file:
    external: true
    name: env-file-${GITHUB_SHA}
    file: ./.env
