apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tml-nft-bot
  name: tml-nft-bot
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30209
  selector:
    app: tml-nft-bot
  type: NodePort
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: statsd-exporter
  name: statsd-exporter
spec:
  ports:
  - port: 9102
    protocol: TCP
    targetPort: 9102
    nodePort: 30210
  selector:
    app: statsd-exporter
  type: NodePort
status:
  loadBalancer: {}