apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tml-nft-bot
  name: tml-nft-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tml-nft-bot
  minReadySeconds: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: tml-nft-bot
    spec:
      containers:
      - image: registry.1webhost.xyz/tml-nft-bot
        imagePullPolicy: Always
        name: tml-nft-bot
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 5
        envFrom:
          - secretRef:
              name: tml-nft-secrets
        resources: {}
      imagePullSecrets:
      - name: regcred

status: {}
