apiVersion: v1
kind: Secret
metadata:
  name: tml-nft-secrets
type: Opaque
data:
  DISCORD_ALL: https://discord.com/api/webhooks/*****
  DISCORD_WEBHOOK_REFLECTION: https://discord.com/api/webhooks/*****
  DISCORD_WEBHOOK_LETTER: https://discord.com/api/webhooks/*****
  DISCORD_WEBHOOK_SYMBOL: https://discord.com/api/webhooks/*****
  DISCORD_WEBHOOK_AURIC: https://discord.com/api/webhooks/*****